export const TABLE_CLASS = "Labe_Classroom"
export const TABLE_STUDENTS = "Labe_Students"
export const TABLE_TEACHERS = "Labe_Teachers"
export const TABLE_STUDENTS_HOBBY = "Labe_Students_Hobby"
export const TABLE_HOBBY = "Labe_Hobby"
export const TABLE_TEACHERS_EXPERTISE = "Labe_Teachers_Expertises"
export const TABLE_EXPERTISE = "Labe_Expertise"